### ISSUE TITLE
User's ways: user can create a tag with an existing name

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#731]
User can create a tag with an existing name. This behavior is observed in the way information section and in jobs tags.

## Steps
1. Create way
2. Create tag with name, e.g. "1"
3. Create another tag with same name

## Actual result
Second tag with name "1" created successfully
![image](https://github.com/tritonJS826/masters-way/assets/4976837/f1335481-d6c0-4bd0-a790-edfd822c40f8)
![image](https://github.com/tritonJS826/masters-way/assets/4976837/102fd277-cbf5-435d-87e7-b8525a76bdad)

## Expected result
User can not create tag with existing name.

**Comment by tritonJS826** [comment]
fixed on the backend, validation shoud be added on the front-end. Minor thing

**Comment by tritonJS826** [comment]
not fixed for labels, maybe it is ok to have the labels by text but different by description and color

**Comment by tritonJS826** [comment]
Refactor for way required (make all way models like store get rid of updateWay logic)

**Comment by tritonJS826** [comment]
should check for is initialized not for some specif fields

**Comment by pp2amd6** [comment]
Implemented for skill tags but still reproduce for job tags


![Image](https://github.com/tritonJS826/masters-way/assets/4976837/7f953be1-3502-47ca-ac5c-812167834459)

**Comment by Ekaterina1994** [comment]
@tritonJS826 So should we allow to create labels with the same name but different description and color as you wrote on the comment below? Or need to add the check?

**Comment by Ekaterina1994** [comment]
Good enough for now. It's not a business requirement.
